# This rule is not used by the project kube-nodepool-manager itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over codefuture.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-nodepool-manager
    app.kubernetes.io/managed-by: kustomize
  name: nodepoolbinding-admin-role
rules:
- apiGroups:
  - codefuture.io
  resources:
  - nodepoolbindings
  verbs:
  - '*'
- apiGroups:
  - codefuture.io
  resources:
  - nodepoolbindings/status
  verbs:
  - get
