---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - codefuture.io
  resources:
  - nodepoolbindings
  - nodepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - codefuture.io
  resources:
  - nodepoolbindings/finalizers
  - nodepools/finalizers
  verbs:
  - update
- apiGroups:
  - codefuture.io
  resources:
  - nodepoolbindings/status
  - nodepools/status
  verbs:
  - get
  - patch
  - update
